name: t_helpers
description: A collection of helper functions to simplify common programming tasks in Dart.
version: 0.0.7+2
repository: https://github.com/tyrcord/t/tree/main/packages/helpers

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.2
  tsub: ^1.2.0
  tmodel: ^0.5.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.2
