name: t_helpers
description: A collection of helper functions to simplify common programming tasks in Dart.
version: 0.0.16
repository: https://github.com/tyrcord/t/tree/main/packages/helpers

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.3.2
  tsub: ^1.3.0
  tmodel: ^0.5.3
  intl: ^0.18.0
  rational: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.2
