name: t_helpers
description: A collection of helper functions to simplify common programming tasks in Dart.
version: 0.0.49+2
repository: https://github.com/tyrcord/t/tree/main/packages/helpers

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  decimal: ^2.3.3
  intl: ^0.18.1
  rational: ^2.2.2
  diacritic: ^0.1.4
  go_router: ^12.1.3

  # T
  tsub: ^1.9.0
  tmodel: ^0.5.12+12
  tenhance: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
