name: t

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  test:
    exec: flutter test
    packageFilters:
      ignore:
        - tbloc_example
        - tmodel
        - tsub
  update:analysis_options:
    exec: $PWD/scripts/update_analysis_options.sh
  sort_imports:
    exec: flutter pub run import_sorter:main
