name: t

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  test:
    exec: flutter test
    packageFilters:
      ignore:
        - tbloc_example
        - tmodel
        - tsub
        - tenhance

  sort:imports:
    exec: flutter pub run import_sorter:main
  update:pubspec:
    exec: python3 $PWD/scripts/update_pubspec.py
  update:analysis_options:
    exec: $PWD/scripts/update_analysis_options.sh
