name: t

packages:
  - packages/**

scripts:
  test: 
    exec: flutter test
    packageFilters:
      ignore:
        - tbloc_example
        - tmodel
        - tsub
  
  sort_imports:
    exec: flutter pub run import_sorter:main