dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
description: 'RxDart Subscriptions management. Provide Apis to store and manage RxDart
  subscriptions and provide methods to unsubscribe them all.

  '
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  rxdart: ^0.27.7
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
homepage: https://github.com/tyrcord/t/tree/main/packages/subx
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/subx/issues
name: subx
version: 1.12.0
