name: subx
version: 1.9.0
description: >
  RxDart Subscriptions management.
  Provide Apis to store and manage RxDart subscriptions
  and provide methods to unsubscribe them all.
homepage: https://github.com/tyrcord/t/tree/main/packages/subx
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/subx/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart: ^0.27.7
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
