name: subx
version: 1.2.0
description: >
  RxDart Subscriptions management.
  Provide Apis to store and manage RxDart subscriptions
  and provide methods to unsubscribe them all.
homepage: https://github.com/tyrcord/t/tree/main/packages/subx
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/subx/issues

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=3.3.0"
  
dependencies:
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rxdart: ^0.27.5
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.1
