dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  t_helpers: ^0.0.53
  tenhance: ^0.0.9
description: A dart library that helps you to logs your app.
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
homepage: https://github.com/tyrcord/t/tree/main/packages/logger
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/issues
name: tlogger
version: 0.0.10+2
