dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  t_helpers: ^0.0.61
  tenhance: ^0.0.15+2
description: A dart library that helps you to logs your app.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <4.0.0"
homepage: https://github.com/tyrcord/t/tree/main/packages/logger
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/issues
name: tlogger
version: 0.0.16+2
