dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.3
  tbloc: ^0.25.2+2
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <4.0.0"
flutter:
  uses-material-design: true
name: tbloc_example
publish_to: none
version: 1.0.0
