name: tbloc_example
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fastyle_dart: ">=1.1.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.1

flutter:
  uses-material-design: true

dependency_overrides:
  tbloc:
    path: ../
