dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  tbloc: ^0.25.5
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.32.0 <4.0.0'
  sdk: '>=3.8.0 <4.0.0'
flutter:
  uses-material-design: true
name: tbloc_example
publish_to: none
version: 1.0.0
