dependencies:
  fastyle_core: ^0.0.48
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  tbloc: ^0.22.1+1
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.16.0'
  sdk: '>=3.2.0 <4.0.0'
flutter:
  uses-material-design: true
name: tbloc_example
publish_to: none
version: 1.0.0
