name: tbloc_example
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  go_router: ^13.0.0

  # T
  tbloc: ^0.21.8+12

  # Fastyle
  fastyle_core: ^0.0.45

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
