name: tbloc_example
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fastyle_dart: ">=1.1.1 <2.0.0"
  tbloc: ^0.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
