name: tstore
description: A dart library that helps you to manage and store entity objects.
version: 0.8.22+7
repository: https://github.com/tyrcord/t/tree/main/packages/tstore
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/tstore/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Public
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  meta: ^1.10.0
  equatable: ^2.0.5
  path: ^1.8.3

  # T
  tmodel: ^0.5.12+12
  tsub: ^1.9.0
  t_helpers: ^0.0.49+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0
