name: tmodel
version: 0.5.1
description: A dart library that helps you to manage model (blueprint) objects.
homepage: https://github.com/tyrcord/t/tree/main/packages/tmodel
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/issues

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.1
