name: tmodel
version: 0.5.4
description: A dart library that helps you to manage model (blueprint) objects.
homepage: https://github.com/tyrcord/t/tree/main/packages/tmodel
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  import_sorter: ^4.6.0
