dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  meta: ^1.15.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  subx: ^1.18.0
  tmodel: ^0.5.19+2
  tuple: ^2.0.2
  uuid: ^4.4.0
description: A dart library that helps you to implement the BLoC pattern.
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: ">=3.24.0"
  sdk: ">=3.5.0 <4.0.0"
homepage: https://github.com/tyrcord/t/tree/main/packages/tbloc
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/tbloc/issues
name: tbloc
version: 0.25.2+2
