name: tbloc
version: 0.21.3+3
description: A dart library that helps you to implement the BLoC pattern.
homepage: https://github.com/tyrcord/t/tree/main/packages/tbloc
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/tbloc/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  async: ^2.11.0
  rxdart: ^0.27.7
  subx: ^1.7.0
  provider: ^6.0.5
  tuple: ^2.0.2
  tmodel: ^0.5.7+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.6
  import_sorter: ^4.6.0
