dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  rational: ^2.2.3
  t_helpers: ^0.0.62
description: A dart library provide a bunch of extenstion.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  flutter: '>=3.29.0 <4.0.0'
  sdk: '>=3.7.0 <4.0.0'
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/enhance/issues
name: tenhance
repository: https://github.com/tyrcord/t/tree/main/packages/enhance
version: 0.0.16
