name: tsub
description: A set of stub files
version: 1.0.0
homepage: https://github.com/tyrcord/t/tree/main/packages/tsub
issue_tracker: https://github.com/tyrcord/t/tree/main/packages/tsub/issues

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.1
