name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter --version
      
      - name: Install and set Melos version
        uses: bluefireteam/melos-action@v3

      - run: melos --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: melos run --no-select analyze

      - name: Run tests
        run: melos run --no-select test
