name: Publish tLogger Package

on:
  push:
    tags:
      - "tlogger-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish_package.yml
    with:
      packageName: "tlogger"
