name: Publish tCache Package

on:
  push:
    tags:
      - "t_cache-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish_package.yml
    with:
      packageName: "t_cache"
