name: Publish tBloC Package

on:
  push:
    tags:
      - "tbloc-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish_package.yml
    with:
      packageName: "tbloc"
