name: Publish tEnhance Package

on:
  push:
    tags:
      - "tenhance-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish_package.yml
    with:
      packageName: "tenhance"
