name: Publish tStore Package

on:
  push:
    tags:
      - "tstore-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish_package.yml
    with:
      packageName: "tstore"
