name: Publish tModel Package

on:
  push:
    tags:
      - "tmodel-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish_package.yml
    with:
      packageName: "tmodel"
