name: Publish Flutter Packages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [new_version]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Code analysis
      - name: Analyze
        run: melos run analyze

      # Run tests
      - name: Test
        run: melos run test

      # Set package versions
      - name: Set package versions
        run: melos version --yes

      - name: Push tags
        run: git push --follow-tags
